export const database = [
    {
        id: '0',
        folder: 'Gustavo Lima',
        order: 'Aleatório',
        crossfade: '1 Segundo',
        time: "05:01:59",
        size: '1354 MB',
        modificationData: '20/01/2022',
        modificationTime: '17:30:59',
        download: '23/01/2022',
        schedules: 'Executar Diariamente',
        date: 'Seg a Sex',
        startTime: '19:00',
        endTime: '22:00',
        tracks: [
            {
                id: "0",
                name: "Ficha Limpa",
                artist: "Gustavo Lima",
                album: "Buteco in Boston",
            },
            {
                id: "1",
                name: "De menina para mulher",
                artist: "Gustavo Lima",
                album: "O embaixador",
            },
            {
                id: "2",
                name: "Balada",
                artist: "Gustavo Lima",
                album: "Gustavo Lima e Voçê",
            },
        ],
    },
    {
        id: '1',
        folder: 'Marilia Mendonça',
        order: 'Sequencial',
        crossfade: '1 segundo',
        time: "03:11:15",
        size: '9665 MB',
        modificationData: '01/01/2022',
        modificationTime: '23:14:59',
        download: '',
        schedules: 'Executar Anuamente',
        date: 'Seg, Qua, Sex',
        startTime: '10:30',
        endTime: '00:00',
        tracks: [
            {
                id: "0",
                name: "Tudo Mundo menos você",
                artist: "Marilia Mendonça",
                album: "Patroas 35%",
            },
            {
                id: "1",
                name: "coração bandido",
                artist: "Marilia Mendonça",
                album: "Patroas",
            },
            {
                id: "2",
                name: "Eu sei de cor",
                artist: "Marilia Mendonça",
                album: "Realidade",
            },
            {
                id: "3",
                name: "Vai lá em casa hoje",
                artist: "Marilia Mendonça",
                album: "Vai lá em casa hoje",
            },
        ],
    },
    {
        id: '2',
        folder: 'Linkin Park',
        order: 'Sequencial',
        crossfade: '1 segundo',
        time: "07:31:35",
        size: '89492 MB',
        modificationData: '06/02/2022',
        modificationTime: '14:00:04',
        download: '01/01/2022',
        schedules: 'Executar Semanalmente',
        date: 'Ter e qui',
        startTime: '22:15',
        endTime: '05:00',
        tracks: [
            {
                id: "0",
                name: "Nunb",
                artist: "Linkin Park",
                album: "Meteora",
            },
            {
                id: "1",
                name: "In The End",
                artist: "Linkin Park",
                album: "Hydrid Theory",
            },
            {
                id: "2",
                name: "Crawling",
                artist: "Linkin Park",
                album: "Hydrid Theory",
            },
            {
                id: "3",
                name: "Somewhere | Belong",
                artist: "Linkin Park",
                album: "Meteora",
            },
        ],
    },
    {
        id: '3',
        folder: 'Ludmilla',
        order: 'Sequencial',
        crossfade: '1 segundo',
        time: "18:25:15",
        size: '8461 MB',
        modificationData: '15/12/2021',
        modificationTime: '22:33:59',
        download: '15/12/2021',
        schedules: 'Executar Semanalmente',
        date: 'Seg a Sab',
        startTime: '01:00',
        endTime: '06:30',
        tracks: [
            {
                id: "0",
                name: "Invocada",
                artist: "Ludmilla",
                album: "Hello mundo",
            },
            {
                id: "1",
                name: "Ele não",
                artist: "Ludmilla",
                album: "Numanice",
            },
            {
                id: "2",
                name: "Rainha da favela",
                artist: "Ludmilla",
                album: "Rainha da favela",
            },
            {
                id: "3",
                name: "Cheguei",
                artist: "Ludmilla",
                album: "A Danada Dou eu",
            },
            {
                id: "4",
                name: "Bom",
                artist: "Ludmilla",
                album: "A Danada Dou eu",
            },
        ],
    },
    {
        id: '4',
        folder: 'Antony & Gabriel',
        order: 'Sequencial',
        crossfade: '1 segundo',
        time: "06:30:05",
        size: '68166 MB',
        modificationData: '17/01/2022',
        modificationTime: '09:30:02',
        download: '08/01/2022',
        schedules: 'Executar Semanalmente',
        date: 'Seg a Dom',
        startTime: '17:45',
        endTime: '23:00',
        tracks: [
            {
                id: "0",
                name: "Agrofarra",
                artist: "Antony & Gabriel",
                album: "Agrofarra",
            },
            {
                id: "1",
                name: "Bebendo mais que Opala",
                artist: "Antony & Gabriel",
                album: "Bonito pra você",
            },
            {
                id: "2",
                name: "Desendeiro",
                artist: "Antony & Gabriel",
                album: "Desendeiro",
            },
            {
                id: "3",
                name: "Raparigueiro da Roça",
                artist: "Antony & Gabriel",
                album: "Antonu e Gabriel",
            },
        ],
    },
    {
        id: '5',
        folder: 'The Black Eyed Peas',
        order: 'Sequencial',
        crossfade: '1 segundo',
        time: "01:15:51",
        size: '61841 MB',
        modificationData: '31/11/2021',
        modificationTime: '21:59:34',
        download: '',
        schedules: 'Executar Semanalmente',
        date: 'Seg a Sex',
        startTime: '14:37',
        endTime: '18:00',
        tracks: [
            {
                id: "0",
                name: "Punp ir Harder",
                artist: "The Black Eyed Peas",
                album: "The E.N.D",
            },
            {
                id: "1",
                name: "Let´s Get it Started",
                artist: "The Black Eyed Peas",
                album: "Elephunk",
            },
            {
                id: "2",
                name: "The Time",
                artist: "The Black Eyed Peas",
                album: "The Beginning",
            },
            {
                id: "3",
                name: "I Gotta Feeling",
                artist: "The Black Eyed Peas",
                album: "The E.N.D",
            },
        ],
    },
    {
        id: '6',
        folder: 'Tribalistas',
        order: 'Aleatório',
        crossfade: '2 segundo',
        time: "04:23:12",
        size: '20226 MB',
        modificationData: '08/08/2022',
        modificationTime: '19:03:46',
        download: '',
        schedules: 'Executar Diariamente',
        date: 'Ter',
        startTime: '18:00',
        endTime: '19:00',
        tracks: [
            {
                id: "0",
                name: "Velha Infância",
                artist: "Tribalistas",
                album: "Tribalistas",
            },
            {
                id: "1",
                name: "Já sei namorar",
                artist: "Tribalistas",
                album: "Tribalistas",
            },
            {
                id: "2",
                name: "Mary Cristo",
                artist: "Tribalistas",
                album: "Tribalistas",
            },
            {
                id: "3",
                name: "É você",
                artist: "Tribalistas",
                album: "Tribalistas",
            },
            {
                id: "4",
                name: "Vilarejo",
                artist: "Tribalistas",
                album: "Ao Vivo",
            },
            {
                id: "5",
                name: "Pecado é lhe deixar de molho",
                artist: "Tribalistas",
                album: "Tribalistas",
            },
            {
                id: "6",
                name: "Um só",
                artist: "Tribalistas",
                album: "Tribalistas",
            },
            {
                id: "7",
                name: "Carnibalismo",
                artist: "Tribalistas",
                album: "Tribalistas",
            },
        ],
    },
];
