export const datacliente = [
  {
    id: '0',
    client: 'Casa e Video',
    number: '220',
    playlist: '4',
    status: false,
  }, 
  {
    id: '1',
    client: 'Lojas da Esquina',
    number: '3',
    playlist: '1',
    status: true,
  },
  {
    id: '2',
    client: 'Pastelaria Limas',
    number: '1',
    playlist: '12',
    status: true,
  }, 
  {
    id: '3',
    client: 'Cadore',
    number: '1',
    playlist: '22',
    status: true,
  }, 
  {
    id: '4',
    client: 'Madeiro',
    number: '20',
    playlist: '2',
    status: false,
  }, 
  {
    id: '5',
    client: 'Condor',
    number: '34',
    playlist: '324',
    status: true,
  }, 
  {
    id: '6',
    client: 'MRV',
    number: '49',
    playlist: '9',
    status: true,
  }, 
  {
    id: '7',
    client: 'Morifarma',
    number: '137',
    playlist: '96',
    status: true,
  }, 
  {
    id: '8',
    client: 'Nissei',
    number: '296',
    playlist: '157',
    status: false,
  }, 
]
